travis:
  secure:
    BINSTAR_TOKEN: n6qQeNNx2+0XzNOCB7olHYPIwNCregKfUWGZghGVsoZrEjTeYTOKXh5qu0ejkTbbyNhbaMc7lckFOIGOai17EzBdyevjPPeI2RYblEQnv8h5Fos9B+4oM1SorMHvcLim/mEu4AF2NoAfX9+uSSWry5d8QYK1SLwWDxuZrNHNXbXNVsUpSAL99KONau9XUC9EuMs2+p7zZg6GCofVCue+K8vvI3OMdYyX9uwY8/bGbTbFgfks7BJl1K2J3NIoolhdJdjKD5V1uW2snBiFskRdOwk5ZMYgZNWI1laSPSxAmn/bMO+LaFKewi8hXn2pmgdAx5fAk9yuDlA1nfyFNz4bA5rPT7k4texTVNiDFTPr9BLiM0yHbC0wP4ezwUFvZ0y/43i0FYpmlDStP0yr0Ie/pH1oxpNLQ6plnoOXvzuUzI5Y+/puvufn0SWxQPOXurVDSETGFIZxrxyxLK6Z10U3O0pDU4ggzaroh4zFvQxaqu+D+8eSGO4hib/Jlqh01z0MwftFyTgVXYi0EI2tqKoG6jx0QjMQnSmUKTFsz1TCcLFNJaaqSWSPaFkHh2vkyH6AYZYLRQvFMkktduaKuFAGwz7wH9Zgl1hX316aXH7Xbn9HcetAilctYIGWhOWZvCMxIuPtO7tb36kxmBt0RcKV+TkUXU4wEtpSAM1uZ5GAMLY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
